# Generated by Django 3.2.14 on 2023-05-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='average',
        ),
    ]
