# Generated by Django 3.2.14 on 2023-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApi', '0004_alter_taskmodel_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
